language: node_js

node_js:
  - "0.10"
#  - "0.11"
#  - "0.12"

services:
  - redis-server
  - mongodb
  - rabbitmq

#branches:
#  only:
#    - master
#    - develop

#matrix:
#  fast_finish: true
#  allow_failures:
#    - node_js: "0.11"
#    - node_js: "0.12"

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - sudo rabbitmqctl status
  - sudo rabbitmq-plugins list
  - npm install -g dredd

deploy:
  provider: heroku
  on: develop
  app: joola-io-example
  api_key:
    secure: u2sgcDddY6is6ZB1q1YsFQwlld0cvsSbfH6UtEVP7QvOeITriv2fauXnt+WTSzLqcLphzFPviUceMP9Qm4FcbKd1+qHHCAtpmZMTx7MXoFjJJXDVYwbL9iQURi5IS6lja8eLSJZk8yonDuWZ6f3babr/iW4o//CalslW5WDwHMs=

script: make test-cov
after_success:
  - make coveralls
  - make -k test-api
 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c4aa904abf1dabb42f95
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false